

logging:
  experiment_name:  Reward_LenResp
  run_name: null
  tags: 
    - "Lenna"
    - "ActionSpace3"
    
  log_dir: ./logs
  tensorboard: true

training:
  num_episodes: 500
  num_steps: 100
  save_model_interval: 50
  target_update_frequency: 1000
  batch_size: 16

  epsilon_decay: 0.995
  epsilon_end: 0.01
  epsilon_start: 1.0

environment:
  camera: 2 
  render: true
  parameters:
    - "CAP_PROP_BRIGHTNESS"
    - "CAP_PROP_CONTRAST"
    - "CAP_PROP_SATURATION"
    # - "CAP_PROP_EXPOSURE"

agent:
  gamma: 0.99
  tau: 0.001
  memory_size: 1000
  learning_rate: 0.001

  type: QAgent
  checkpoint: null #"mlartifacts\913919034547846327\1dfce4cfb0314d68be5e5e8d87c4d020\artifacts\20241230_072757_final.pth
